PSCAT/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PSCAT.Models;
using PSCAT.ViewModels;
using PSCAT.Data;

namespace PSCAT.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Dashboard()
        {
            List<StudentScore> stu = _context.StudentScores.Where(s => s.StudentID == "student1").ToList();


            StudentDashboardViewModel testDetails = new StudentDashboardViewModel();
            testDetails.StudentId = "student1";

            foreach (StudentScore ts in stu)
            {
                var details = _context.Tests.Where(s => s.TestID == ts.TestID).FirstOrDefault();

                TestDetails temp = new TestDetails
                {
                    TestName = details.TestName,
                    TestId = ts.TestID,
                    Course = details.CourseID,
                    CourseId = details.CourseID,
                    Marks = ts.MarksScored.ToString(),
                    MaxMarks = details.MaxMarks.ToString(),
                    PassOrFail = ts.MarksScored >= Convert.ToInt32(details.CutOffMarks) ? "Y" : "N"
                };


                testDetails.TestDetail.Add(temp);

            }

            return View(testDetails);
        }

        public IActionResult TestDetails(string studentId, string testId, string courseId)
        {
            StudentTestRecords record = _context.StudentTestRecords.Where(s=>s.StudentId == studentId && s.TestId == testId && s.CourseId == courseId).FirstOrDefault();
            


            return View(record);
        }

        public IActionResult Tests()
        {
            List<StudentTestStatus> pendingTests = _context.StudentTestStatus.Where(s=>s.Completed == "N" && s.StudentId == "student1").ToList();

            TestStatusViewModel pendingTestCompleteDetails = new TestStatusViewModel();

            foreach(var rec in pendingTests)
            {
                var det = _context.Tests.Where(s=> s.TestID == rec.TestId && s.StaffID == rec.StaffId && s.CourseID == rec.CourseId).FirstOrDefault();

                var courseDet = _context.StaffCourses.Where(s=>s.CourseID == rec.CourseId && s.StaffID == rec.StaffId).FirstOrDefault();

                var staffDet = _context.Staff.Where(s=>s.StaffID == rec.StaffId).FirstOrDefault();

                StudentTestStatusRecord temp = new StudentTestStatusRecord();
                temp.CourseId = det.CourseID;
                temp.CourseName = courseDet.CourseName;
                temp.StaffId = det.StaffID;
                temp.StaffName = staffDet.StaffName;
                temp.StudentId = rec.StudentId;
                temp.Completed = rec.Completed;
                temp.TestId = rec.TestId;
                temp.TestName = det.TestName;



                pendingTestCompleteDetails.StudentTestStatusRecord.Add(temp);
            }


            return View(pendingTestCompleteDetails);
        }
        public IActionResult ImproveMe()
        {
            return View();
        }
    }
}

PSCAT/Controllers/TeacherPDController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PSCAT.Models;
using PSCAT.Services;
using PSCAT.Data;

namespace PSCAT.Controllers
{
    public class TeacherPDController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TeacherPDController(ApplicationDbContext context)
        {
            _context = context;
        }
        private TeacherPD tps;
        public IActionResult TeacherPD()
        {
            return View();
        }

        public IActionResult Questionnaire()
        {
            CourseProcess courseprocess = new CourseProcess(_context);
            QuestionAns questionnaire = new QuestionAns();
            questionnaire.staffcourses = courseprocess.getCourses();
            return View(questionnaire);
        }

        public IActionResult Review()
        {
            return View();
        }
        public IActionResult QuestionAnsSub(QuestionAns qAns)
        {
            tps = new TeacherPD(_context);

            Boolean saveStatus= tps.saveQuestion(qAns);
            if (saveStatus == true)
                return View("success");
            else
                return View("failToSave"); 
            
            return View("success");

        }

    }

}

PSCAT/Views/Shared/FailToSave.cshtml
The enetered data is failed to save. Please verify and renter it.

PSCAT/Views/Shared/Success.cshtml
Question is entered successfully.

PSCAT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSCAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PSCAT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Teacher PD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Questionnaire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Review</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PSCAT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PSCAT/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSCAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PSCAT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Teacher PD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Questionnaire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Review</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PSCAT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PSCAT/Views/Shared/_StudentLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSCAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Students" asp-action="Dashboard">PSCAT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Tests">Tests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="ImproveMe">Improve Me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PSCAT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PSCAT/Views/Shared/_TeacherLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSCAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 justify-content-center">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item" style="background-color:#eee;">
                            <a class="nav-link text-dark active"  asp-area="" asp-controller="TeacherPD" asp-action="TeacherPD">TeacherPD</a>
                        </li>
                        <li class="nav-item" style="background-color:#eee;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherPD" asp-action="Questionnaire">Questionnaire</a>
                        </li>
                        <li class="nav-item" style="background-color:#eee;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherPD" asp-action="Review">Review</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PSCAT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>